{{- if .Values.podIdentity.enabled -}}
{{- $resourceIdFormat := "/subscriptions/%s/resourceGroups/%s/providers/Microsoft.ManagedIdentity/userAssignedIdentities/%s" -}}
{{- $subscriptionId := (required "subscriptionId is missing" .Values.podIdentity.subscriptionId) -}}
{{- $resourceGroup := (required "resourceGroup is missing" .Values.podIdentity.resourceGroupName) -}}
{{- $azureIdentityName := (required "azureIdentityName is missing" .Values.podIdentity.azureIdentityName) -}}
{{- $resourceId := printf $resourceIdFormat $subscriptionId $resourceGroup $azureIdentityName -}}

apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ template "wdatp-service.name" . }}
    helm.sh/chart: {{ template "wdatp-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  azureIdentity: {{ .Release.Name }}
  selector: {{ .Release.Name }}
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ template "wdatp-service.name" . }}
    helm.sh/chart: {{ template "wdatp-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: 0
  resourceID: {{ $resourceId }}
  clientID: {{ required "azureIdentityClientId is missing" .Values.podIdentity.azureIdentityClientId | quote }}
{{- end -}}